apiVersion: v1
kind: Service
metadata:
  name: {{ include "celery-scale-operator-chart.fullname" . }}-controller-manager-metrics-service
  labels:
    control-plane: controller-manager
  {{- include "celery-scale-operator-chart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.metricsService.type }}
  selector:
    app.kubernetes.io/name: celery-scale-operator
    control-plane: controller-manager
    {{- include "celery-scale-operator-chart.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.metricsService.ports | toYaml | nindent 2 }}
